const data = {
  products: [
    {
      name: "Puma jeans pant",
      slug: "puma-jeans-pant",
      category: "Pant",
      image: "https://static-01.daraz.com.bd/p/000f6e9ea9666a5aaf60a9758359798d.jpg",
      price: 120,
      brand: " Puma",
      rating: 4.5,
      numReviews: 10,
      countInStock: 10,
      description: "This is high quality jeans pant",
    },
    {
      name: "Puma Gabardine pant",
      slug: "puma-gabardine-pant",
      category: "Pant",
      image: "https://richmanbd.com/wp-content/uploads/2022/10/26a-600x600.jpg",
      price: 100,
      brand: " Puma",
      rating: 4,
      numReviews: 12,
      countInStock: 15,
      description: "This is high quality gabardine pant",
    },
    {
      name: "Adidas Formal Shirt",
      category: "Shirt",
      image: "https://static-01.daraz.com.bd/p/5556e3915dce8030a324c0b32af45384.jpg",
      price: 80,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 17,
      slug: "adidas-formal-shirt",
      countInStock: 0,
      description: "This is high quality formal shirt",
    },
    {
      name: "Adidas Casual Shirt",
      category: "Shirt",
      image: "https://static-01.daraz.com.bd/p/bd50c44d49d6f5c0f6815178318456ae.jpg",
      price: 70,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 9,
      slug: "adidas-casual-shirt",
      countInStock: 35,
      description: "This is high quality casual shirt",
    },
    {
      name: "Khan Ladies jacket",
      category: "Jacket",
      image: "https://static-01.daraz.com.bd/p/1cde47f86873055f8e53416d9c37ae0a.jpg",
      price: 200,
      brand: "Khan",
      rating: 4,
      numReviews: 11,
      slug: "khan-ladies-jacket",
      countInStock: 20,
      description: "This is high quality ladies jacket",
    },
    {
      name: "Khan Mens jacket",
      category: "Jacket",
      image: "https://static-01.daraz.com.bd/p/91ef91080bf3546e956c0b3e8b2e5c82.jpg",
      price: 240,
      brand: "Khan",
      rating: 3.5,
      numReviews: 18,
      slug: "khan-mens-jacket",
      countInStock: 30,
      description: "This is high quality men's jacket",
    },
  ],
};

export default data;
